"""The saved W&B view for one experiment group: what a reviewer sees, in the
order they need it, with the words that make each panel readable without the
code (``docs/acl/design/dashboard.md`` §7).

Four sections, one per review question — Verdict, Mechanism, Trust, Detail.
Each opens with a text panel that states the population, unit and cadence of
the graphs under it, then the line plots for the kept metrics of that group
(:mod:`training.dashboard.metrics`). Runs are grouped by training distribution
so arms overlay with a min–max band over seeds. Smoothing is off everywhere: a
point is drawn only where a number was computed.

The text is filled from the group's ``wandb.config`` (:class:`RunFacts`), so
the same builder serves every suite.
"""
from __future__ import annotations

import dataclasses
from typing import Dict, List, Mapping, Sequence, Tuple

import wandb_workspaces.reports.v2 as panels
import wandb_workspaces.workspaces as workspaces
from wandb_workspaces import expr

from training.dashboard.metrics import KEPT, Group, Metric, budget_key, has_budget

X_AXIS = "environment_steps"
GROUP_RUNS_BY = "context_distribution"  # the arm of the experiment
DEPLOYMENT_EVALUATION = "evaluation/deployment"
UNIFORM_EVALUATION = "evaluation/uniform"

# Panel grid: 24 columns wide; a text panel spans the width, plots are half width.
TEXT_PANEL_HEIGHT = 5
PLOT_WIDTH, PLOT_HEIGHT = 12, 8


@dataclasses.dataclass(frozen=True)
class RunFacts:
    """The facts about a run that the text panels state, read from ``wandb.config``."""

    num_timesteps: int
    num_evals: int
    num_eval_envs: int
    episode_length: int
    safety_bound: float
    deployment_distribution: str
    context_space: Tuple[Tuple[str, Tuple[float, float]], ...]  # (dimension, (low, high)), in Ω's order
    num_rounds: int
    environment_steps_per_round: int

    def __post_init__(self) -> None:
        if self.num_evals < 2:
            raise ValueError("num_evals must be at least 2 (an initial evaluation and one after training)")

    @classmethod
    def from_wandb_config(cls, config: Mapping[str, object]) -> "RunFacts":
        """Raises ``KeyError`` naming the missing key when a run predates the dashboard."""
        return cls(
            num_timesteps=int(float(config["num_timesteps"])),
            num_evals=int(config["num_evals"]),
            num_eval_envs=int(config["num_eval_envs"]),
            episode_length=int(config["episode_length"]),
            safety_bound=float(config["safety_bound"]),
            deployment_distribution=str(config["deployment_distribution"]),
            context_space=tuple((name, (float(low), float(high))) for name, (low, high) in config["context_space"].items()),
            num_rounds=int(config["num_rounds"]),
            environment_steps_per_round=int(config["environment_steps_per_round"]),
        )

    @property
    def steps_between_evaluations(self) -> int:
        return self.num_timesteps // (self.num_evals - 1)

    @property
    def context_dimensions(self) -> Sequence[str]:
        return tuple(name for name, _ in self.context_space)

    def describe_context_space(self) -> str:
        return ", ".join(f"{name} ∈ [{low:.3g}, {high:.3g}]" for name, (low, high) in self.context_space)


def verdict_text(facts: RunFacts) -> str:
    return (
        f"**Frozen policy**, evaluated {facts.num_evals} times over the run, every "
        f"{facts.steps_between_evaluations:,} environment steps, {facts.num_eval_envs} episodes per evaluation. "
        f"**One point per evaluation; the segments between points are not data.** "
        f"**Deployment** = `{facts.deployment_distribution}`; **Uniform Ω** = contexts drawn uniformly from Ω "
        f"({facts.describe_context_space()}). "
        f"Return and cost are **sums over one episode** (≤ {facts.episode_length} steps), mean over the "
        f"{facts.num_eval_envs} episodes. Reward is the suite's scaled reward. Cost is the number of steps in "
        f"violation; the second line is the budget **{facts.safety_bound:g} per episode** — a policy is safe when "
        f"its cost is under it. Lines: one per training distribution, mean over seeds, band = min–max."
    )


def mechanism_text(facts: RunFacts) -> str:
    return (
        f"What the student trained on and how the constraint reacted. **One point per round** "
        f"(= one PPO training step = {facts.environment_steps_per_round:,} environment steps; "
        f"{facts.num_rounds} rounds). The heatmaps (auto-generated by W&B under `training_curriculum`) "
        f"cut Ω into fixed bins; colour = share of the round's **transitions** (experienced, q̂) or "
        f"**completed episodes** (sampled, q) in that bin — they differ when episode length depends on the "
        f"context. *Mean context* is the mean of those two distributions, the form that overlays across arms; "
        f"*intended* is the value a staged or fixed distribution states. λ is PPO-Lagrange's multiplier after "
        f"the round. *Training cost/return per episode*: mean over the training episodes that **ended in the "
        f"round**, under whatever contexts the distribution sampled, with exploration noise — not comparable "
        f"to Verdict's numbers; the budget line is the same {facts.safety_bound:g}."
    )


def trust_text(facts: RunFacts) -> str:
    return (
        f"Is the run healthy enough to believe the sections above? One point per round unless stated. "
        f"*Training episode length*: mean over training episodes that ended in the round; "
        f"{facts.episode_length} = full length, a collapse to a few steps means the policy falls or freezes. "
        f"*Evaluation spread*: std over the {facts.num_eval_envs} evaluation episodes, one point per "
        f"evaluation — how noisy each Verdict point is. *Completed episodes per round*: the sample size behind "
        f"the sampled-context histogram. *Throughput* and *compiles* come from the performance tracker "
        f"(`--measure_performance`); any compile after the first round means an array shape changed."
    )


def detail_text(facts: RunFacts) -> str:
    return (
        f"Everything else we keep, same cadences as above. `training/cost_violation` is the **per-transition** "
        f"cost of the PPO batch minus the budget per step ({facts.safety_bound:g} / {facts.episode_length} = "
        f"{facts.safety_bound / facts.episode_length:.4g}); multiply by {facts.episode_length} for per-episode "
        f"units. Losses are PPO's. Forward reward and constrained speed are episode sums (÷ length = per step)."
    )


SECTION_TEXT = {
    Group.VERDICT: verdict_text,
    Group.MECHANISM: mechanism_text,
    Group.TRUST: trust_text,
    Group.DETAIL: detail_text,
}
OPEN_SECTIONS = (Group.VERDICT, Group.MECHANISM)


@dataclasses.dataclass(frozen=True)
class Plot:
    """One line panel: several series on one y-axis."""

    title: str
    series: Tuple[str, ...]
    unit: str


EVALUATIONS = ((DEPLOYMENT_EVALUATION, "deployment"), (UNIFORM_EVALUATION, "uniform Ω"))


def _concrete_keys(metric: Metric, facts: RunFacts) -> List[Tuple[str, str]]:
    """``(panel title, key)`` for every instance of the metric's pattern in this run."""
    if "{evaluation}" in metric.pattern:
        return [(f"{metric.panel_title} on {label}", metric.key(evaluation=evaluation)) for evaluation, label in EVALUATIONS]
    if "{dimension}" in metric.pattern:
        return [(f"{metric.panel_title} — {dimension}", metric.key(dimension=dimension)) for dimension in facts.context_dimensions]
    return [(metric.panel_title, metric.pattern)]


def plots_for(group: Group, facts: RunFacts) -> List[Plot]:
    """The line panels of one section, in registry order; metrics sharing a panel title share a panel.

    Histogram metrics are not line panels: W&B renders them as heatmaps in its
    auto-generated `training_curriculum` section.
    """
    series_by_title: Dict[str, List[str]] = {}
    unit_by_title: Dict[str, str] = {}
    for metric in KEPT:
        if metric.group is not group or metric.histogram:
            continue
        for title, key in _concrete_keys(metric, facts):
            series = series_by_title.setdefault(title, [])
            series.append(key)
            if has_budget(key):
                series.append(budget_key(key))
            unit_by_title[title] = metric.unit
    return [Plot(title, tuple(series), unit_by_title[title]) for title, series in series_by_title.items()]


def _line_panel(plot: Plot, layout: panels.Layout) -> panels.LinePlot:
    return panels.LinePlot(
        title=plot.title,
        x=X_AXIS,
        y=list(plot.series),
        title_x="environment steps",
        title_y=plot.unit,
        smoothing_type="none",
        groupby=panels.Config(GROUP_RUNS_BY),
        groupby_aggfunc="mean",
        groupby_rangefunc="minmax",
        layout=layout,
    )


def _section(group: Group, facts: RunFacts) -> workspaces.Section:
    text = panels.MarkdownPanel(markdown=SECTION_TEXT[group](facts), layout=panels.Layout(x=0, y=0, w=24, h=TEXT_PANEL_HEIGHT))
    line_panels = [
        _line_panel(
            plot,
            panels.Layout(x=(index % 2) * PLOT_WIDTH, y=TEXT_PANEL_HEIGHT + (index // 2) * PLOT_HEIGHT, w=PLOT_WIDTH, h=PLOT_HEIGHT),
        )
        for index, plot in enumerate(plots_for(group, facts))
    ]
    return workspaces.Section(
        name=group.value,
        panels=[text, *line_panels],
        is_open=group in OPEN_SECTIONS,
        pinned=group is Group.VERDICT,
        panel_settings=workspaces.SectionPanelSettings(x_axis=X_AXIS, smoothing_type="none"),
    )


def build_view(entity: str, project: str, group_name: str, facts: RunFacts) -> workspaces.Workspace:
    """The workspace for one experiment group, ready to ``save()``."""
    return workspaces.Workspace(
        entity=entity,
        project=project,
        name=group_name,
        sections=[_section(group, facts) for group in Group],
        settings=workspaces.WorkspaceSettings(
            x_axis=X_AXIS,
            smoothing_type="none",
            point_visualization_method="bucketing",
            group_by_prefix="first",
        ),
        runset_settings=workspaces.RunsetSettings(
            filters=f"Group = '{group_name}'",
            groupby=[expr.Config(GROUP_RUNS_BY)],
        ),
    )
